[versions]
# annotations
jetbrains-annotations = "26.0.2-1"

# serialization
jackson             = "2.20.0-rc1"
jackson-annotations = "3.0-rc5"
jackson-bom         = "2.20.0-rc1"
jackson-parent      = "2.20-rc1"

# logging
slf4j   = "2.0.17"
tinylog = "2.8.0-M1"

# xmpp
jxmpp = "1.1.0"
mdns = "1.1.1"
smack = "4.5.0-rc1"
bcprov = "1.83"

# swing
flatlaf = "3.7"
miglayout = "11.4.2"

[libraries]
# annotations
annotations         = { group = "org.jetbrains"             , name = "annotations"        , version.ref = "jetbrains-annotations" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-annotations"   }
jackson-bom         = { group = "com.fasterxml.jackson"     , name = "jackson-bom"        , version.ref = "jackson-bom"           }
jackson-parent      = { group = "com.fasterxml.jackson"     , name = "jackson-parent"     , version.ref = "jackson-parent"        }

# serialization
jackson-core        = { group = "com.fasterxml.jackson.core", name = "jackson-core"    , version.ref = "jackson" }
jackson-databind    = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }

# logging
slf4j-api     = { group = "org.slf4j"  , name = "slf4j-api"    , version.ref = "slf4j"   }
tinylog-api   = { group = "org.tinylog", name = "tinylog-api"  , version.ref = "tinylog" }
tinylog-impl  = { group = "org.tinylog", name = "tinylog-impl" , version.ref = "tinylog" }
tinylog-slf4j = { group = "org.tinylog", name = "slf4j-tinylog", version.ref = "tinylog" }

# xmpp
jxmpp         = { group = "org.jxmpp"               , name = "jxmpp-core"            , version.ref = "jxmpp"  }
jxmpp-jid     = { group = "org.jxmpp"               , name = "jxmpp-jid"             , version.ref = "jxmpp"  }
mdns          = { group = "org.minidns"             , name = "minidns-core"          , version.ref = "mdns"   }
smack-xml     = { group = "org.igniterealtime.smack", name = "smack-xmlparser"       , version.ref = "smack"  }
smack-xmlstax = { group = "org.igniterealtime.smack", name = "smack-xmlparser-stax"  , version.ref = "smack"  }
smack-core    = { group = "org.igniterealtime.smack", name = "smack-core"            , version.ref = "smack"  }
smack-stream  = { group = "org.igniterealtime.smack", name = "smack-streammanagement", version.ref = "smack"  }
smack-tcp     = { group = "org.igniterealtime.smack", name = "smack-tcp"             , version.ref = "smack"  }
smack-ext     = { group = "org.igniterealtime.smack", name = "smack-extensions"      , version.ref = "smack"  }
bcprov        = { group = "org.bouncycastle"        , name = "bcprov-jdk18on"        , version.ref = "bcprov" }

# swing
flatlaf        = { group = "com.formdev"  , name = "flatlaf"                , version.ref = "flatlaf"   }
flatlaf-themes = { group = "com.formdev"  , name = "flatlaf-intellij-themes", version.ref = "flatlaf"   }
miglayout      = { group = "com.miglayout", name = "miglayout-swing"        , version.ref = "miglayout" } 

[bundles]
annotations = [
  "annotations",
  "jackson-annotations",
  "jackson-bom",
  "jackson-parent"
]

serialization = [
  "jackson-core",
  "jackson-databind",
  "jackson-annotations",
  "jackson-bom",
  "jackson-parent"
]

logging = [
  "slf4j-api",
  "tinylog-api",
  "tinylog-impl",
  "tinylog-slf4j"
]

xmpp = [
  "jxmpp",
  "jxmpp-jid",
  "mdns",
  "smack-xml",
  "smack-xmlstax",
  "smack-core",
  "smack-stream",
  "smack-tcp",
  "smack-ext",
  "bcprov"
]

swing = [
  "flatlaf",
  "flatlaf-themes",
  "miglayout"
]
